version: "3.6"
services:

  # https://hub.docker.com/r/_/postgres/
  db:
    # replace username/repo:tag with your name and image details
    image: postgres
    ports:
      # This image includes EXPOSE 5432 (the postgres port), so standard container linking will make it automatically available to the linked containers.
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: daw
      POSTGRES_USER: daw
      POSTGRES_PASSWORD: daw_grupo_7
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgres
    networks:
      - app

  webapp:
    image: hellodalao/daw
    links:
      - db
    depends_on:
      - db
    ports:
      - "443:8443"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/daw
    networks:
      - app
networks:
  app: